In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
news = pd.read_csv('data/market_news.csv')
prices = pd.read_csv('data/prices.csv')

news.head()

,date,source,category,headline
0,2020-01-08,Интерфакс,Прочее,Опубликован годовой ESG-отчёт компании
1,2020-01-10,CRU,Фосфаты,DAP дешевеет из-за слабого спроса в Индии
2,2020-01-18,Профильный телеграм-канал,Логистика,"Ставки фрахта снижаются, логистика дешевеет"
3,2020-03-12,ICIS,Аммиак,Котировки аммиака пошли вниз на фоне слабого с...
4,2020-03-14,CRU,Прочее,Компания провела ежегодный день инвестора

In [3]:
prices.head()

,date,urea_price,dap_price,mop_price,gas_price,ammonia_price,brent_oil,usd_rub,freight_index,crop_price_index,sulphur_price,phosphate_rock_price,potash_supply_index,consensus_price_urea
0,2020-01-06,378.4,600.0,464.1,28.0,486.0,72.5,65.02,2000.0,104.4,140.0,170.0,100.0,337.8
1,2020-01-13,338.2,564.2,457.7,25.4,423.5,71.4,64.68,1934.0,103.9,148.8,167.5,98.5,357.5
2,2020-01-20,365.6,553.7,484.5,27.7,458.6,72.1,65.34,1887.0,109.8,141.5,150.7,98.6,366.5
3,2020-01-27,367.3,564.3,524.2,30.1,475.9,71.8,65.64,1866.0,105.5,153.2,156.2,98.9,358.1
4,2020-02-03,358.6,578.6,488.8,24.9,481.6,72.4,65.90,1830.0,106.4,138.6,152.6,99.2,377.2